#!/bin/zsh -l

#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -C haswell
#SBATCH --mem=8GB

source activate multime

export LD_PRELOAD=/global/homes/c/cjlloyd/.conda/envs/multime/lib/libgfortran.so.3
module swap PrgEnv-intel PrgEnv-gnu

srun python simulate_knockout.py $1 $2 $3 $4 $5 $6
