#!/bin/zsh -l

#SBATCH -p shared
#SBATCH -N 1
#SBATCH -t 00:45:00
#SBATCH -C haswell
#SBATCH --mem=8GB

module load python/3.6-anaconda-4.4
source activate multime

export LD_PRELOAD=/global/homes/c/cjlloyd/.conda/envs/multime/lib/libgfortran.so.3
module swap PrgEnv-intel PrgEnv-gnu

srun python simulate_knockout.py $1 $2 $3 $4 $5
