met_to_name = {'2dmmq8': '2-Demethyl-\nmenaquinone 8',
 '2fe2s': '2Fe-2S',
 '4fe4s': '4Fe-4S',
 'adocbl': 'Adenosyl-\ncobalamin',
 'ala__L': 'L-Alanine',
 'arg__L': 'L-Arginine',
 'asn__L': 'L-Asparagine',
 'asp__L': 'L-Aspartate',
 'bmocogdp': 'bis-MGD',
 'btn': 'Biotin',
 'coa': 'Coenzyme A',
 'cys__L': 'L-Cysteine',
 'gln__L': 'L-Glutamine',
 'glu__L': 'L-Glutamate',
 'gly': 'Glycine',
 'gthox': 'Glutathione',
 'hemeO': 'Heme O',
 'his__L': 'L-Histidine',
 'ile__L': 'L-Isoleucine',
 'leu__L': 'L-Leucine',
 'lys__L': 'L-Lysine',
 'met__L': 'L-Meth skionine',
 'mqn8': 'Menaquinone 8',
 'nad': 'NAD',
 'nadp': 'NADP',
 'phe__L': 'L-Phenylalanine',
 'pheme': 'Protoheme',
 'pro__L': 'L-Proline',
 'pydx5p': "Pyridoxal \n 5'-phosphate",
 'q8': 'Ubiquinone-8',
 'ribflv': 'Riboflavin',
 'ser__L': 'L-Serine',
 'sheme': 'Siroheme',
 'thf': 'Tetrahydrofolate',
 'thmpp': 'Thiamine \n diphosphate',
 'thr__L': 'L-Threonine',
 'trp__L': 'L-Tryptophan',
 'tyr__L': 'L-Tyrosine',
 'val__L': 'L-Valine'}

aas_to_name = {
 'ala__L': 'L-Alanine',
 'arg__L': 'L-Arginine',
 'asn__L': 'L-Asparagine',
 'asp__L': 'L-Aspartate',
 'cys__L': 'L-Cysteine',
 'gln__L': 'L-Glutamine',
 'glu__L': 'L-Glutamate',
 'gly': 'Glycine',
 'his__L': 'L-Histidine',
 'ile__L': 'L-Isoleucine',
 'leu__L': 'L-Leucine',
 'lys__L': 'L-Lysine',
 'met__L': 'L-Methionine',
 'phe__L': 'L-Phenylalanine',
 'pro__L': 'L-Proline',
 'ser__L': 'L-Serine',
 'thr__L': 'L-Threonine',
 'trp__L': 'L-Tryptophan',
 'tyr__L': 'L-Tyrosine',
 'val__L': 'L-Valine'}